using FastFood.Cliente;
using FastFood.Pedido;
using FastFood.Produtos;

Clientes cliente = new Clientes();
cliente.idcliente = 001;
cliente.situacaocliente = "Ativo";
cliente.nome = "Maria Fulana";
cliente.sexo = "F";
cliente.cpf = "123456789";
cliente.telefone = "1234-5678";
cliente.celular = "998776453";
cliente.email = "mariafulana@teste.com.br";
cliente.cidade = "São Paulo";
cliente.rua = "ABC";
cliente.numero = "123";
cliente.complemento = " ";
cliente.bairro = "Grande";
cliente.cep = "12341234";

Pedidos pedido = new Pedidos();
pedido.solicitante = cliente;
pedido.numpedido = 001;
pedido.frete = 10.00;
pedido.total = 12.00 + pedido.frete;
pedido.tipopagamento = "Cartão";
pedido.datapedido = "23/11/2022";

Produtos produto = new Produtos();
produto.solicitante = pedido;
produto.categoria = "Padaria";
produto.nomeproduto = "Pão Francês";
produto.valor = 1.50;
produto.quantidade = 8;
produto.marca = "Monte Castelo";

Console.WriteLine("Compra Número = " + pedido.solicitante.idcliente);
Console.WriteLine("==========================================");
Console.WriteLine("Cliente = " + pedido.solicitante.nome);
Console.WriteLine("Sexo = " + pedido.solicitante.sexo);
Console.WriteLine("CPF = " + pedido.solicitante.cpf);
Console.WriteLine("Telefone = " + pedido.solicitante.telefone);
Console.WriteLine("Celular = " + pedido.solicitante.celular);
Console.WriteLine("E-mail = " + pedido.solicitante.email);
Console.WriteLine("Cidade = " + pedido.solicitante.cidade);
Console.WriteLine("Rua = " + pedido.solicitante.rua);
Console.WriteLine("Número = " + pedido.solicitante.numero);
Console.WriteLine("Complemento" + pedido.solicitante.complemento);
Console.WriteLine("Bairro = " + pedido.solicitante.bairro);
Console.WriteLine("CEP = " + pedido.solicitante.cep);
Console.WriteLine("==========================================");
Console.WriteLine("Produto = " + produto.nomeproduto);
Console.WriteLine("Categoria = " + produto.categoria);
Console.WriteLine("Marca = " + produto.marca);
Console.WriteLine("Quantidade = " + produto.quantidade);
Console.WriteLine("Valor Unitário = " + produto.valor);
Console.WriteLine("Quantidade da Compra * Valor Unitário = " + (produto.quantidade * produto.valor));
Console.WriteLine("Frete = " + produto.solicitante.frete);
Console.WriteLine("Total + Frete = " + produto.solicitante.total);
Console.WriteLine("Forma de pagamento = " + produto.solicitante.tipopagamento);
Console.WriteLine("Data da Compra = " + produto.solicitante.datapedido);
Console.WriteLine("=================== FIM =======================");

Clientes cliente1 = new Clientes();
cliente1.idcliente = 002;
cliente1.situacaocliente = "Ativo";
cliente1.nome = "João Cicrano";
cliente1.sexo = "M";
cliente1.cpf = "876543211";
cliente1.telefone = "9876-5432";
cliente1.celular = "333444999";
cliente1.email = "joaocicrano@teste.com.br";
cliente1.cidade = "São Paulo";
cliente1.rua = "DEF";
cliente1.numero = "432";
cliente1.complemento = "Apto C";
cliente1.bairro = "Pequeno";
cliente1.cep = "44332288";

Pedidos pedido1 = new Pedidos();
pedido1.solicitante = cliente1;
pedido1.numpedido = 002;
pedido1.frete = 18.50;
pedido1.total = 73.00 + pedido.frete;
pedido1.tipopagamento = "Cartão";
pedido1.datapedido = "22/11/2022";

Produtos produto1 = new Produtos();
produto1.solicitante = pedido1;
produto1.categoria = "Pizzaria";
produto1.nomeproduto = "Pizza Romana - Combo Família + Refri";
produto1.valor = 73.00;
produto1.quantidade = 1;
produto1.marca = "Império das Pizzas";

Console.WriteLine("Compra Número = " + pedido1.solicitante.idcliente);
Console.WriteLine("==========================================");
Console.WriteLine("Cliente = " + pedido1.solicitante.nome);
Console.WriteLine("Sexo = " + pedido1.solicitante.sexo);
Console.WriteLine("CPF = " + pedido1.solicitante.cpf);
Console.WriteLine("Telefone = " + pedido1.solicitante.telefone);
Console.WriteLine("Celular = " + pedido1.solicitante.celular);
Console.WriteLine("E-mail = " + pedido1.solicitante.email);
Console.WriteLine("Cidade = " + pedido1.solicitante.cidade);
Console.WriteLine("Rua = " + pedido1.solicitante.rua);
Console.WriteLine("Número = " + pedido1.solicitante.numero);
Console.WriteLine("Complemento" + pedido1.solicitante.complemento);
Console.WriteLine("Bairro = " + pedido1.solicitante.bairro);
Console.WriteLine("CEP = " + pedido1.solicitante.cep);
Console.WriteLine("==========================================");
Console.WriteLine("Produto = " + produto1.nomeproduto);
Console.WriteLine("Categoria = " + produto1.categoria);
Console.WriteLine("Marca = " + produto1.marca);
Console.WriteLine("Quantidade = " + produto1.quantidade);
Console.WriteLine("Valor Unitário = " + produto1.valor);
Console.WriteLine("Quantidade da Compra * Valor Unitário = " + (produto1.quantidade * produto1.valor));
Console.WriteLine("Frete = " + produto1.solicitante.frete);
Console.WriteLine("Total + Frete = " + produto1.solicitante.total);
Console.WriteLine("Forma de pagamento = " + produto1.solicitante.tipopagamento);
Console.WriteLine("Data da Compra = " + produto1.solicitante.datapedido);
Console.WriteLine("=================== FIM =======================");

